 add_newline = true


 [character]
 success_symbol = "[](bold purple)"
 error_symbol = "[](bold red) "

 [status]
 style = "bg:red"
 
 [hostname]
 disabled = false
 

 [conda]
 format = "(bold red) [$symbol$environment](bold yellow) "

 [git_branch]
 style = "bold yellow"
 format = "(bold red) [$symbol$branch]($style) "
 
 [git_status]
 style = "bold yellow"


 [directory]
 truncation_length = 10
 truncate_to_repo = false
 format = "(bold red)[$path]($style)[$read_only]($read_only_style) "
 style = "bold yellow"

 [package]
 format = "(bold red) [$symbol$version]($style) "


 [nodejs]
 format = "(bold red) [$symbol($version )]($style)"

