#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI

bspc config border_width        2
bspc config focused_border_color 
bspc config border_radius	5
bspc config window_gap          3
bspc config top_padding 	20
bspc config right_padding	3
bspc config left_padding	3
bspc config side_padding	3
bspc config split_ratio          1.0
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true
#bspc config border_radius 		 6
bspc config pointer_modifier	mod1
bspc config swallow_first_click true


bspc rule -a kitty desktop='^2'


polybar main &
picom &
nitrogen --restore &
nm-applet &
xfce4-clipman &
lxpolkit &
