#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d       嗢 阮  ﭮ 


bspc config border_width        2
bspc config focused_border_color 
bspc config border_radius	5
bspc config window_gap          7
bspc config top_padding 	5
bspc config right_padding	3
bspc config left_padding	3
bspc config side_padding	3
bspc config split_ratio          1.0
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true
#bspc config border_radius 		 6
bspc config pointer_modifier	mod1
bspc config swallow_first_click true


bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Brave-browser desktop='^1'
bspc rule -a kitty desktop='^2'
bspc rule -a Pcmanfm desktop='^3'
bspc rule -a Code  desktop='^4'
bspc rule -a vlc desktop='^5'
bspc rule -a Spotify desktop='^6'
bspc rule -a Rhythmbox desktop='^6'
bspc rule -a Nomacs desktop='^7'
bspc rule -a discord desktop='^8'
bspc rule -a Font-manager desktop='^9'
bspc rule -a Qalculate-gtk desktop="^9"


bspc rule -a Nitrogen state=floating
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

polybar main &

picom &
nitrogen --restore &
mpd &
nm-applet &
xfce4-clipman &
pamac-tray &
